language: cpp
compiler:
  - gcc

sudo: required

befor_install:
  - sudo apt-get update -qq
  - sudo apt-get install openssl openssl-dev cmake -qq

script:
  - cmake .
  - make
  - EasyBitcoinTest

after_success:
  - make clean