//
// Created by Sebastian on 24.05.2015.
//

#ifndef EASYBITCOIN_CONSTANTS_H
#define EASYBITCOIN_CONSTANTS_H

#define EC_PRIVATE_KEY_LENGTH 32
#define EC_PUBLIC_KEY_LENGTH 65
#define EC_COMPRESSED_PUBLIC_KEY_LENGTH 33

#endif //EASYBITCOIN_CONSTANTS_H
