//
// Created by Sebastian on 24.05.2015.
//

#ifndef EASYBITCOIN_CONSTANTS_H
#define EASYBITCOIN_CONSTANTS_H

#define EC_PRIVATE_KEY_LENGTH 32
#define EC_PUBLIC_KEY_LENGTH 65
#define EC_COMPRESSED_PUBLIC_KEY_LENGTH 33

//OP codes
#define OP_DUP 0x76
#define OP_HASH160 0xa9
#define OP_EQUAL 0x87
#define OP_EQUALVERIFY 0x88
#define OP_CHECKSIG 0xac

#endif //EASYBITCOIN_CONSTANTS_H
